#include "lut_writer.h"

#include <algorithm>
#include <cmath>
#include <iomanip>
#include <limits>
#include <stdexcept>
#include <string>

namespace otlut {
namespace {

void validateCommonSize(int size) {
  if (size < 2 || size > 129) {
    throw std::invalid_argument("LUT size must be between 2 and 129.");
  }
}

int quantize(double value, int bitDepth) {
  const long long maxValue = (1LL << bitDepth) - 1LL;
  const double clamped = std::clamp(value, 0.0, 1.0);
  return static_cast<int>(std::llround(clamped * maxValue));
}

std::string lowerExtension(const std::string& path) {
  const std::size_t dot = path.find_last_of('.');
  if (dot == std::string::npos) return {};
  std::string ext = path.substr(dot);
  std::transform(ext.begin(), ext.end(), ext.begin(),
                 [](unsigned char c) { return static_cast<char>(std::tolower(c)); });
  return ext;
}

}  // namespace

bool isSupportedCubeSize(int size) {
  return size >= 2 && size <= 129;
}

bool isSupportedThreeDlSize(int size) {
  return size == 2 || size == 3 || size == 5 || size == 9 || size == 17 ||
         size == 33 || size == 65 || size == 129;
}

int threeDlInputBitDepthForSize(int size) {
  for (int bitDepth = 0; bitDepth <= 7; ++bitDepth) {
    if ((1 << bitDepth) + 1 == size) return bitDepth;
  }
  throw std::invalid_argument(
      ".3dl size must be one of 2, 3, 5, 9, 17, 33, 65, or 129.");
}

void writeIdentityCube(std::ostream& output, const IdentityLutOptions& options) {
  validateCommonSize(options.size);

  output << "# Generated by otlut\n";
  output << "TITLE \"" << options.title << "\"\n";
  output << "LUT_3D_SIZE " << options.size << "\n";
  output << "DOMAIN_MIN 0.0 0.0 0.0\n";
  output << "DOMAIN_MAX 1.0 1.0 1.0\n";

  output << std::fixed << std::setprecision(9);

  // OpenToonz's .cube path consumes entries in file order as an RGB texture.
  // Emit blue fastest, then green, then red: the common .cube convention.
  const double denominator = static_cast<double>(options.size - 1);
  for (int r = 0; r < options.size; ++r) {
    for (int g = 0; g < options.size; ++g) {
      for (int b = 0; b < options.size; ++b) {
        output << (r / denominator) << ' ' << (g / denominator) << ' '
               << (b / denominator) << '\n';
      }
    }
  }
}

void writeIdentityThreeDl(std::ostream& output,
                          const IdentityLutOptions& options) {
  const int inputBitDepth = threeDlInputBitDepthForSize(options.size);
  if (options.outputBitDepth < 1 || options.outputBitDepth > 30) {
    throw std::invalid_argument(".3dl output bit depth must be from 1 to 30.");
  }

  output << "# Generated by otlut\n";
  output << "3DMESH\n";
  output << "Mesh " << inputBitDepth << ' ' << options.outputBitDepth << "\n";

  const long long gridMax = (1LL << options.outputBitDepth) - 1LL;
  for (int i = 0; i < options.size; ++i) {
    if (i) output << ' ';
    const double value =
        static_cast<double>(i) / static_cast<double>(options.size - 1);
    output << static_cast<long long>(std::llround(value * gridMax));
  }
  output << '\n';

  const double denominator = static_cast<double>(options.size - 1);
  for (int r = 0; r < options.size; ++r) {
    for (int g = 0; g < options.size; ++g) {
      for (int b = 0; b < options.size; ++b) {
        output << quantize(r / denominator, options.outputBitDepth) << ' '
               << quantize(g / denominator, options.outputBitDepth) << ' '
               << quantize(b / denominator, options.outputBitDepth) << '\n';
      }
    }
  }
}

LutFormat formatFromPath(const std::string& path) {
  const std::string ext = lowerExtension(path);
  if (ext == ".cube") return LutFormat::Cube;
  if (ext == ".3dl") return LutFormat::ThreeDl;
  throw std::invalid_argument(
      "Cannot infer LUT format. Use an output path ending in .cube or .3dl.");
}

}  // namespace otlut
