#include "lut_writer.h"

#include <algorithm>
#include <cctype>
#include <cmath>
#include <iomanip>
#include <stdexcept>
#include <string>

namespace otlut {
namespace {

int quantize(double value, int bitDepth) {
  const long long maxValue = (1LL << bitDepth) - 1LL;
  const double clamped = std::clamp(value, 0.0, 1.0);
  return static_cast<int>(std::llround(clamped * maxValue));
}

std::string lowerExtension(const std::string& path) {
  const std::size_t dot = path.find_last_of('.');
  if (dot == std::string::npos) return {};
  std::string ext = path.substr(dot);
  std::transform(ext.begin(), ext.end(), ext.begin(),
                 [](unsigned char c) {
                   return static_cast<char>(std::tolower(c));
                 });
  return ext;
}

void validateLut(const Lut3D& lut) {
  if (lut.size < 2 || lut.size > 129) {
    throw std::invalid_argument("LUT size must be between 2 and 129.");
  }
  const size_t expected =
      static_cast<size_t>(lut.size) * lut.size * lut.size * 3;
  if (lut.rgb.size() != expected) {
    throw std::invalid_argument("LUT data size does not match grid size.");
  }
}

}  // namespace

bool isSupportedCubeSize(int size) {
  return size >= 2 && size <= 129;
}

bool isSupportedThreeDlSize(int size) {
  return size == 2 || size == 3 || size == 5 || size == 9 || size == 17 ||
         size == 33 || size == 65 || size == 129;
}

int threeDlInputBitDepthForSize(int size) {
  for (int bitDepth = 0; bitDepth <= 7; ++bitDepth) {
    if ((1 << bitDepth) + 1 == size) return bitDepth;
  }
  throw std::invalid_argument(
      ".3dl size must be one of 2, 3, 5, 9, 17, 33, 65, or 129.");
}

void writeCube(std::ostream& output, const Lut3D& lut,
               const LutWriteOptions& options) {
  validateLut(lut);

  output << "# Generated by otlut\n";
  output << "TITLE \"" << options.title << "\"\n";
  output << "LUT_3D_SIZE " << lut.size << "\n";
  output << "DOMAIN_MIN 0.0 0.0 0.0\n";
  output << "DOMAIN_MAX 1.0 1.0 1.0\n";
  output << std::fixed << std::setprecision(9);

  const size_t cells = static_cast<size_t>(lut.size) * lut.size * lut.size;
  for (size_t cell = 0; cell < cells; ++cell) {
    output << lut.rgb[cell * 3 + 0] << ' ' << lut.rgb[cell * 3 + 1] << ' '
           << lut.rgb[cell * 3 + 2] << '\n';
  }
}

void writeThreeDl(std::ostream& output, const Lut3D& lut,
                  const LutWriteOptions& options) {
  validateLut(lut);
  const int inputBitDepth = threeDlInputBitDepthForSize(lut.size);
  if (options.outputBitDepth < 1 || options.outputBitDepth > 30) {
    throw std::invalid_argument(".3dl output bit depth must be from 1 to 30.");
  }

  output << "# Generated by otlut\n";
  output << "3DMESH\n";
  output << "Mesh " << inputBitDepth << ' ' << options.outputBitDepth << "\n";

  const long long gridMax = (1LL << options.outputBitDepth) - 1LL;
  for (int i = 0; i < lut.size; ++i) {
    if (i) output << ' ';
    const double value =
        static_cast<double>(i) / static_cast<double>(lut.size - 1);
    output << static_cast<long long>(std::llround(value * gridMax));
  }
  output << '\n';

  for (int r = 0; r < lut.size; ++r) {
    for (int g = 0; g < lut.size; ++g) {
      for (int b = 0; b < lut.size; ++b) {
        const size_t sourceCell =
            static_cast<size_t>(r) * lut.size * lut.size +
            static_cast<size_t>(g) * lut.size + b;

        // OpenToonz rearranges .3dl file order into texture order.
        output << quantize(lut.rgb[sourceCell * 3 + 0],
                           options.outputBitDepth)
               << ' '
               << quantize(lut.rgb[sourceCell * 3 + 1],
                           options.outputBitDepth)
               << ' '
               << quantize(lut.rgb[sourceCell * 3 + 2],
                           options.outputBitDepth)
               << '\n';
      }
    }
  }
}

void writeIdentityCube(std::ostream& output, int size,
                       const LutWriteOptions& options) {
  writeCube(output, makeIdentityLut(size), options);
}

void writeIdentityThreeDl(std::ostream& output, int size,
                          const LutWriteOptions& options) {
  writeThreeDl(output, makeIdentityLut(size), options);
}

LutFormat formatFromPath(const std::string& path) {
  const std::string ext = lowerExtension(path);
  if (ext == ".cube") return LutFormat::Cube;
  if (ext == ".3dl") return LutFormat::ThreeDl;
  throw std::invalid_argument(
      "Cannot infer LUT format. Use an output path ending in .cube or .3dl.");
}

}  // namespace otlut
